######################################################################
# Automatically generated by qmake (2.01a) to 19. okt 15:49:22 2006
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = editdelegate
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += bardelegate.h
SOURCES += bardelegate.cpp main.cpp
