######################################################################
# Automatically generated by qmake (2.01a) må 16. okt 15:40:21 2006
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = splitterview
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
