######################################################################
# Automatically generated by qmake (2.01a) on 18. okt 19:40:38 2006
######################################################################

QT += core gui
greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TEMPLATE = app
TARGET = stringlist
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
